### PR TITLE
Fixed field work inside ACF Pro repeater. Fixes #4

### LINKED ISSUE #4: Incorrect work inside ACF Repeater
Picker works incorrectly when used inside ACF Pro Repeater. Looks like its JS part doesn't expect multiple pickers on same page so when video is being selected - its thumbnail get updated into all pickers. Moreover when page with multiple pickers get submitted - it stores incorrect (sometimes even no) values into ACF structures. These problems currently makes your (otherwise great) plugin to be used in all scenarios.

### PR DESCRIPTION
**Pull request by FlyingDR**
These changes fixes #4. Tested with Wordpress 4.4.2 and ACF Pro 5.3.6.1

### CODE REVIEW

**Comment by airesvsg** [comment]
Hi @FlyingDR,
Thank you for your help me.
I tested, but the error persists.
Thanks

----

I will rewrite the plugin [YouTube Picker](https://github.com/airesvsg/youtubepicker) and when I implement this new version in the [ACF YouTube Picker](https://github.com/airesvsg/acf-youtubepicker) I will to fix this error.

----
acf-youtubepicker

----

Wordpress 4.4.2 and ACF Pro 5.3.6.1

**Comment by FlyingDR** [comment]
Ok, however that is strange. Reason of the problem is that your jQuery selector for holder incorrectly takes multiple nodes. Maybe it will help you to find correct solution, mine was just a quick fix since your plugin was required for my current project.

**Comment by airesvsg** [comment]
Hi @FlyingDR,
I rewrote the plugin YouTubePicker (https://github.com/airesvsg/youtubepicker).
I'll update this add-on soon.
Thanks

**Comment by FlyingDR** [comment]
@airesvsg Thank you for information, will wait for update

**Comment by airesvsg** [comment]
Hi @FlyingDR,
new version available.
Thanks

**Comment by FlyingDR** [comment]
Thanks!

**Pull request closed without merging**
