### PR TITLE
Using HTTPS for thumbnails if needed

### PR DESCRIPTION
**Pull request by jay-oswald**
Checks if the server is running HTTPS and fetches thumbnails as HTTPS as
to not deliver mixed content

### CODE REVIEW

**Comment by airesvsg** [comment]
Hi @jay-oswald,
Thanks for the PR.

What do you think if you only remove the protocol?
```PHP
<img src="//i.ytimg.com/vi/<?php echo esc_attr( $v['vid'] ); ?>/default.jpg">
```

**Comment by jay-oswald** [comment]
Yeah that would be better, I'm not used to doing that yet haha

**Comment by airesvsg** [comment]
@jay-oswald Please make this change and resubmit your PR.

**Comment by jay-oswald** [comment]
Changes made

**Comment by airesvsg** [comment]
Thanks

**Pull request merged**
